// Flag emoji for each team name appearing in the matches/long-term picks.
// Includes Swedish + English spellings + common alternates so it works for both
// the matches table (English) and bracket/profile inputs (Swedish).
const FLAGS: Record<string, string> = {
  // English (matches table)
  "Algeria": "🇩🇿",
  "Argentina": "🇦🇷",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Belgium": "🇧🇪",
  "Bolivia": "🇧🇴",
  "Bosnia": "🇧🇦",
  "Bosnien": "🇧🇦",
  "Brazil": "🇧🇷",
  "Canada": "🇨🇦",
  "Cape Verde": "🇨🇻",
  "Colombia": "🇨🇴",
  "Côte d'Ivoire": "🇨🇮",
  "Croatia": "🇭🇷",
  "Curaçao": "🇨🇼",
  "Czechia": "🇨🇿",
  "DR Kongo": "🇨🇩",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Haiti": "🇭🇹",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Italien": "🇮🇹",
  "Italy": "🇮🇹",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Mexico": "🇲🇽",
  "Morocco": "🇲🇦",
  "Netherlands": "🇳🇱",
  "New Zealand": "🇳🇿",
  "Norway": "🇳🇴",
  "Panama": "🇵🇦",
  "Paraguay": "🇵🇾",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Senegal": "🇸🇳",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Spain": "🇪🇸",
  "Switzerland": "🇨🇭",
  "Tunisia": "🇹🇳",
  "Turkiet": "🇹🇷",
  "Turkey": "🇹🇷",
  "Ukraina": "🇺🇦",
  "Ukraine": "🇺🇦",
  "Uruguay": "🇺🇾",
  "USA": "🇺🇸",
  "Uzbekistan": "🇺🇿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  // Swedish alternates (used in bracket/profile picks)
  "Mexiko": "🇲🇽",
  "Sydafrika": "🇿🇦",
  "Sydkorea": "🇰🇷",
  "Tjeckien": "🇨🇿",
  "Kanada": "🇨🇦",
  "Schweiz": "🇨🇭",
  "Brasilien": "🇧🇷",
  "Marocko": "🇲🇦",
  "Skottland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Australien": "🇦🇺",
  "Turkiet ": "🇹🇷",
  "Tyskland": "🇩🇪",
  "Komorerna": "🇰🇲",
  "Elfenbenskusten": "🇨🇮",
  "Nederländerna": "🇳🇱",
  "Sverige": "🇸🇪",
  "Tunisien": "🇹🇳",
  "Belgien": "🇧🇪",
  "Syrien": "🇸🇾",
  "Nya Zeeland": "🇳🇿",
  "Spanien": "🇪🇸",
  "Eritrea": "🇪🇷",
  "Saudiarabien": "🇸🇦",
  "Frankrike": "🇫🇷",
  "Irak": "🇮🇶",
  "Norge": "🇳🇴",
  "Ungern": "🇭🇺",
  "Jordanien": "🇯🇴",
  "Nigeria": "🇳🇬",
  "Kroatien": "🇭🇷",
  "TBD": "🏳️",
};

export function teamFlag(name: string | null | undefined): string {
  if (!name) return "";
  return FLAGS[name.trim()] ?? "🏳️";
}
