// Flag emoji for each team name appearing in the matches/long-term picks.
// Includes Swedish + English spellings + common alternates so it works for both
// the matches table (English) and bracket/profile inputs (Swedish).
const FLAGS: Record<string, string> = {
  // English
  "algeria": "🇩🇿",
  "argentina": "🇦🇷",
  "australia": "🇦🇺",
  "austria": "🇦🇹",
  "belgium": "🇧🇪",
  "bolivia": "🇧🇴",
  "bosnia": "🇧🇦",
  "brazil": "🇧🇷",
  "cameroon": "🇨🇲",
  "canada": "🇨🇦",
  "cape verde": "🇨🇻",
  "chile": "🇨🇱",
  "china": "🇨🇳",
  "china pr": "🇨🇳",
  "colombia": "🇨🇴",
  "comoros": "🇰🇲",
  "congo dr": "🇨🇩",
  "costa rica": "🇨🇷",
  "côte d'ivoire": "🇨🇮",
  "ivory coast": "🇨🇮",
  "croatia": "🇭🇷",
  "cuba": "🇨🇺",
  "curaçao": "🇨🇼",
  "czechia": "🇨🇿",
  "czech republic": "🇨🇿",
  "denmark": "🇩🇰",
  "dr congo": "🇨🇩",
  "dr kongo": "🇨🇩",
  "ecuador": "🇪🇨",
  "egypt": "🇪🇬",
  "el salvador": "🇸🇻",
  "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "eritrea": "🇪🇷",
  "france": "🇫🇷",
  "germany": "🇩🇪",
  "ghana": "🇬🇭",
  "greece": "🇬🇷",
  "guatemala": "🇬🇹",
  "haiti": "🇭🇹",
  "honduras": "🇭🇳",
  "hungary": "🇭🇺",
  "indonesia": "🇮🇩",
  "iran": "🇮🇷",
  "iraq": "🇮🇶",
  "italy": "🇮🇹",
  "jamaica": "🇯🇲",
  "japan": "🇯🇵",
  "jordan": "🇯🇴",
  "kenya": "🇰🇪",
  "mali": "🇲🇱",
  "mexico": "🇲🇽",
  "morocco": "🇲🇦",
  "netherlands": "🇳🇱",
  "new zealand": "🇳🇿",
  "nigeria": "🇳🇬",
  "norway": "🇳🇴",
  "panama": "🇵🇦",
  "paraguay": "🇵🇾",
  "peru": "🇵🇪",
  "philippines": "🇵🇭",
  "poland": "🇵🇱",
  "portugal": "🇵🇹",
  "qatar": "🇶🇦",
  "romania": "🇷🇴",
  "saudi arabia": "🇸🇦",
  "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "senegal": "🇸🇳",
  "serbia": "🇷🇸",
  "slovakia": "🇸🇰",
  "south africa": "🇿🇦",
  "south korea": "🇰🇷",
  "spain": "🇪🇸",
  "sweden": "🇸🇪",
  "switzerland": "🇨🇭",
  "syria": "🇸🇾",
  "tanzania": "🇹🇿",
  "trinidad and tobago": "🇹🇹",
  "trinidad & tobago": "🇹🇹",
  "tunisia": "🇹🇳",
  "turkey": "🇹🇷",
  "ukraine": "🇺🇦",
  "united states": "🇺🇸",
  "uruguay": "🇺🇾",
  "usa": "🇺🇸",
  "uzbekistan": "🇺🇿",
  "venezuela": "🇻🇪",
  "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "zambia": "🇿🇲",
  "zimbabwe": "🇿🇼",
  // Swedish
  "algeriet": "🇩🇿",
  "australien": "🇦🇺",
  "belgien": "🇧🇪",
  "bosnien": "🇧🇦",
  "brasilien": "🇧🇷",
  "danmark": "🇩🇰",
  "elfenbenskusten": "🇨🇮",
  "egypten": "🇪🇬",
  "filippinerna": "🇵🇭",
  "frankrike": "🇫🇷",
  "grekland": "🇬🇷",
  "indonesien": "🇮🇩",
  "irak": "🇮🇶",
  "italien": "🇮🇹",
  "jordanien": "🇯🇴",
  "kanada": "🇨🇦",
  "kina": "🇨🇳",
  "kap verde": "🇨🇻",
  "komorerna": "🇰🇲",
  "kroatien": "🇭🇷",
  "marocko": "🇲🇦",
  "mexiko": "🇲🇽",
  "nederländerna": "🇳🇱",
  "nigeria": "🇳🇬",
  "norge": "🇳🇴",
  "nya zeeland": "🇳🇿",
  "österrike": "🇦🇹",
  "peru": "🇵🇪",
  "polen": "🇵🇱",
  "rumänien": "🇷🇴",
  "saudiarabien": "🇸🇦",
  "schweiz": "🇨🇭",
  "serbien": "🇷🇸",
  "skottland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "slovakien": "🇸🇰",
  "spanien": "🇪🇸",
  "sydafrika": "🇿🇦",
  "sydkorea": "🇰🇷",
  "syrien": "🇸🇾",
  "sverige": "🇸🇪",
  "tjeckien": "🇨🇿",
  "tunisien": "🇹🇳",
  "turkiet": "🇹🇷",
  "ukraina": "🇺🇦",
  "ungern": "🇭🇺",
  "venezuela": "🇻🇪",
  "tbd": "🏳️",
  // ISO alpha-3 codes used in some DB entries
  "dza": "🇩🇿",
  "civ": "🇨🇮",
  "cod": "🇨🇩",
  "cpv": "🇨🇻",
  "kor": "🇰🇷",
  "ksa": "🇸🇦",
  "irn": "🇮🇷",
  "irq": "🇮🇶",
  "uru": "🇺🇾",
};

export function teamFlag(name: string | null | undefined): string {
  if (!name) return "";
  return FLAGS[name.trim().toLowerCase()] ?? "🏳️";
}

export function TeamFlag({ name, className }: { name: string | null | undefined; className?: string }) {
  const flag = teamFlag(name);
  if (!name) return null;
  return <span title={name} className={className}>{flag}</span>;
}
